### ISSUE TITLE
Fatal error on Prework (for Bazel) step

### ISSUE THREAD

**Issue by crojas119** [google/silifuzz#11]
Hello!
I would like to know if this is a real error or something I'm missing during the setup.
A few weeks ago I was able to installed in same config with no issues and now is showing the error shown in the image attached when trying to execute the bazel build command.

OS i'm using is:
Ubuntu 20.04

![Silifuzz-error](https://github.com/google/silifuzz/assets/112655124/998d9ba3-d9c6-4b87-b688-5730f7c93d59)

**Comment by ksteuck** [comment]
"<compare>" is a C++20 header so it looks like a possible compiler misconfiguration. Are you running inside a Docker container or using the host system to build the code?

**Comment by crojas119** [comment]
I'm using the host to build the code.

**Comment by ksteuck** [comment]
it must be the compiler version then. Make sure you have clang >= 16 (`clang --version`). You can override the version Bazel uses by setting the `$CC` envvar. HTH

**Comment by crojas119** [comment]
Updating!
I change to Ubuntu 22.04 with kernel 6.2.0 and can build without issues.
