### ISSUE TITLE
Issue with orchestrator

### ISSUE THREAD

**Issue by pluviophilee** [google/silifuzz#15]
Hello,

I encountered an issue when trying to run the orchestrator. I followed the installation and deployment steps, but when executing the following command:
./orchestrator/silifuzz_orchestrator_main --duration=30s --runner=./runner/reading_runner_main_nolibc --shard_list_file=/tmp/shard_list

I received the following error:

E0712 15:28:49.543153 1266434 silifuzz_orchestrator_main.cc:224] Could not open file: No such file or directory

Upon investigating the silifuzz_orchestrator_main.cc file, it appears that the program fails to read the corpus_metadata_file, possibly due to the file path not being provided or incorrect.

Could you please provide guidance on how to resolve this issue? Is there a specific format or location where this file should be placed?

Thank you for your help!

**Comment by ksteuck** [comment]
Hi @pluviophilee

The file is text-formatted [CorpusMetadata protobuf](https://github.com/google/silifuzz/blob/5424d762593e49458078bd38823cc12f608c2d00/proto/corpus_metadata.proto#L20). E.g. the following will work:
```
version: "my_corpus_version"
```

**Comment by pluviophilee** [comment]
Hello @ksteuck 

Thank you for the previous help regarding the corpus_metadata_file. Following your instructions, I was able to run the command successfully. However, I encountered another issue while executing the following command:

"${SILIFUZZ_BIN_DIR}/external/com_google_fuzztest/centipede/centipede" \
  --binary="${SILIFUZZ_BIN_DIR}/proxies/unicorn_x86_64" \
  --workdir=/tmp/wd

The command executes and outputs "new feature: ******", but I also receive the following warnings:

W0719 14:49:48.526754 1903594 centipede_default_callbacks.cc:87] Custom mutator undetected or misbehaving:
W0719 14:49:48.526766 1903594 centipede_default_callbacks.cc:90] Falling back to internal default mutator

How can I address this issue to ensure the custom mutator is detected and functions correctly?

Any guidance on resolving these warnings would be greatly appreciated.

**Comment by ksteuck** [comment]
```
W0719 14:49:48.526754 1903594 centipede_default_callbacks.cc:87] Custom mutator undetected or misbehaving:
W0719 14:49:48.526766 1903594 centipede_default_callbacks.cc:90] Falling back to internal default mutator
```
this is normal and expected for the proxies that come with silifuzz. If you're interested in implemented a custom mutator, please refer to Centipede [source code](https://github.com/google/fuzztest/blob/main/centipede/centipede_default_callbacks.h#L44)
