### ISSUE TITLE
Questions Size of Snapshot

### ISSUE THREAD

**Issue by ChrisLaspias** [google/silifuzz#5]
Hi silifuzz,

I use Silifuzz as part of my research and after walking a while through the codebase I wanted to ask you some questions. 

1. Is there a way to define the number of instructions that the snapshot will contain (e.g after fuzzing unicorn the number of x86 instructions that a snapshot will contain ) ? Is it possible to create bigger snapshots (e.g containing 1000 instructions)? The paper mentions : "Our typical snapshot contains less than 100 bytes of code and runs in microseconds, but it can be arbitrarily large."
2. Is there a way to check the size of a snapshot and more specifically get the number of instructions executed? 
Thank you in advance

**Comment by ksteuck** [comment]
Hi @ChrisLaspias 

1. The sample proxies SiliFuzz provides do not have an option to define the exact number of instructions. Instead, there's an upper limit that is currently set to 100 for [x86](https://github.com/google/silifuzz/blob/main/proxies/unicorn_x86_64.cc#L40) and 4096  for [aarch64](https://github.com/google/silifuzz/blob/main/proxies/unicorn_aarch64.cc#L49). Both numbers are "more of a guideline" i.e. there's no guarantee this limit will ever be reached. Generally, snapshots can be arbitrary large both in terms of the number of dynamic instruction and in terms of how much memory they map. We have experimented with both larger and smaller snapshots, and found that smaller snapshots work better for our use case.
2. You can use [`snap_tool trace`](https://github.com/google/silifuzz/blob/main/tools/snap_tool.cc#L550) command to produce the trace (currently, x86-only). This will execute the snapshot and print every instruction.

**Comment by ChrisLaspias** [comment]
Hi @ksteuck ,
Thank you for the quick answer.

**Comment by ksteuck** [comment]
the answer depends on what you mean by "dynamic linking". The runner binary is always linked fully statically.
```
$ file bazel-bin/runner/reading_runner_main_nolibc
bazel-bin/runner/reading_runner_main_nolibc: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, BuildID[xxHash]=394d49c23eedd37a, not stripped
```

 There are then two ways to load the corpus file into the runner. The default is to [read corpus from a file](https://github.com/google/silifuzz#snap) (aka reading runner). 

There's also an option to codegen [Snapshots => C++](https://github.com/google/silifuzz/blob/main/snap/gen/snap_generator.h#L90) that can then be compiled into a self-contained (baked-in) runner binary. This latter option doesn't have good tooling around it and may be deprecated in the future. You can see an example of how this is done [here](https://github.com/google/silifuzz/blob/main/snap/testing/BUILD#L103).  But the TL;DR is `genrule() => C++ => cc_library() => cc_binary()`

HTH

**Comment by ChrisLaspias** [comment]
@ksteuck 
Thank you very much for helping. That was exactly what I was looking for.
